name: 🚀 Run unittests on pull requests

on:
  pull_request:
    branches: [main]
      types: [opened, reopened, synchronize]

jobs:
  test:
    name: 🚀 Run unittests on pull requests
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 🚀 Run unittests
        shell: bash
        run: python3 -m unittest tests.py
